#!/bin/busybox /bin/sh
export PATH=/usr/bin:/usr/sbin:/bin:/sbin

# Mount the dev directory
mount -t devtmpfs none /dev

# Mount the rest of the directory
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -n -t tmpfs    tmpfs    /run

echo -e "\nBoot took $(cut -d' ' -f1 /proc/uptime) seconds\n" > /dev/kmsg

echo -e "**********    Loading kernel modules     **********\n" > /dev/kmsg
echo -e "Loading: leds_gpio\n" > /dev/kmsg
modprobe -q leds_gpio
echo -e "Loading: led_class\n" > /dev/kmsg
modprobe -q led_class

armoryctl led white on
sleep 2

armoryctl led blue on
mount /dev/{ROOTFS_DEV}p2 /root
armoryctl led blue off
armoryctl led white off
# Switch root
exec switch_root -c /dev/console /root /sbin/init
