#!/bin/busybox /bin/sh
export PATH=/usr/bin:/usr/sbin:/bin:/sbin

# Mount the dev directory
mount -t devtmpfs none /dev

# Mount the rest of the directory
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -n -t tmpfs    tmpfs    /run

exec /bin/sh
